name: example
description: Annotates data classes for XML deserialization
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  logging: ^0.11.4
  xml: ^4.4.0
  runtime:
    path: ../runtime/

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^0.10.3
  test: ^1.14.4
  generator:
    path: ../generator/
