name: generator
description: Annotates data classes for XML deserialization
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  analyzer: "0.39.14"
  build: ^1.3.0
  build_config: ^0.4.0
  code_builder: ^3.0.0
  recase: ^3.0.0
  runtime:
    path: ../runtime/
  source_gen: ^0.9.6
  xml: ^4.4.1

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^1.2.1
  mockito: ^4.1.0
  pedantic: ^1.9.0
  test: ^1.14.4
