# 
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: generator
description: Annotates data classes for XML deserialization
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  build: ^1.3.0
  build_config: ^0.4.0
  built_collection: ^4.3.1
  built_value: ^7.1.0
  code_builder: ^3.0.0
  logging: ^0.11.4
  recase: ^3.0.0
  runtime:
    path: ../runtime/
  source_gen: ^0.9.6
  xml: ^4.4.1

dev_dependencies:
  build_runner: ^1.0.0
  build_test: ^1.2.1
  built_value_generator: ^7.1.0
  pedantic: ^1.9.0
  test: ^1.14.4
