# 
# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: instant_xml_parser
description: Code generator for instant_xml_parser. Reads specially annotated Dart code an emits an XML parser/deserializer to match.
version: 1.1.1+1
homepage: https://github.com/sarahec/instant_xml_parser

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  analyzer: ^2.0.0
  build: ^2.0.3
  build_config: ^1.0.0
  code_builder: ^4.1.0
  collection: ^1.15.0
  dart_style: ^2.0.3
  logging: ^1.0.1
  meta: ^1.2.4
  recase: ^4.0.0
  ixp_runtime: ^1.1.0
  source_gen: ^1.0.5
  xml: ^5.1.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.0.0

